### ISSUE TITLE
Bug: The website is not secure.

### ISSUE THREAD

**Issue by QinxinTian** [itsdax/Traverse#81]
<img width="934" alt="2017-11-06 7 22 15" src="https://user-images.githubusercontent.com/25886116/32441010-9bc40c7e-c2c3-11e7-96d4-cb978de28856.png">
If it is secure, the left hand side of the address should be green.

**Comment by itsdax** [comment]
we don't force redirect for https, so both http and https are usable. Heres the secure link https://traverse.dax.cloud/
